### ISSUE TITLE
Rename scripts to .user.js

### ISSUE THREAD

**Issue by sc0ttkclark** [moderntribe/tampermonkey-scripts#1]
If you rename the scripts and add `.user.js` to them, then clicking raw will automatically open up Tampermonkey and prompt to install the script. This will also allow updates to be retrieved :)

**Comment by sc0ttkclark** [comment]
Not sure about how updates work though, just noticed this when installing another user script from another GitHub repo.

**Comment by sc0ttkclark** [comment]
Example, see how this one works when you click to raw:
https://github.com/m5n/netflix-ratings-extractor/blob/master/netflix-ratings-extractor.user.js

**Comment by borkweb** [comment]
Addressed by: #2
